### ISSUE TITLE
How to test spring lemon with auto configuration?

### ISSUE THREAD

**Issue by xiewenya** [naturalprogrammer/spring-lemon#10]
I try to learn from spring-lemon by writing some test cases for it. But both MockMailSender and SmtpMailSender are created in the applicationContext. It seems like that the LemonAutoConfiguration  class is not to be loaded.  Could you provide some example of test a auto configuration project?

 Here is my configuration:

```java
@SpringBootApplication
public class LemonTest implements ApplicationContextAware{
    private ApplicationContext context;

    public static void main(String[] args){
        SpringApplication.run(LemonTest.class, args);
        System.out.println("haha");
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.context = applicationContext;
    }
}
```

```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class InitTest {
    @Autowired
    private MailSender mailSender;

    @Test
    public void test(){
        assertNotNull(mailSender);
    }
}
```

**Comment by naturalprogrammer** [comment]
Not sure what would be the best practices to test auto configuration.

Nonetheless, not sure how both SmtpMailSender and MockMailSender would be created at the same time, because, then the application should throw "multiple bean error" when starting.

As I understand, you aren't asking about how to write API tests, but in case you are, the samples are there in the demo project.
