### ISSUE TITLE
Lemon & Spring cloud?

### ISSUE THREAD

**Issue by qwertukg** [naturalprogrammer/spring-lemon#17]
What about Spring Cloud cooperation? I mean Spring Lemon its more for monolith, or it have some ineraction with Spring Cloud

**Comment by naturalprogrammer** [comment]
Evolving Spring Lemon to make it conducive for microservices is in my to-do list ( although I don't think I can get to it anytime soon). Currently it shouldn't block you from including it in individual microservices and use only needed features, but I think we can split it into a few libraries - e.g. segregating the user module, so that only user-microservice includes that.

**Comment by qwertukg** [comment]
Are u mean use Lemon only for microsevices development?

**Comment by naturalprogrammer** [comment]
For both, microservices as well as monoliths.

**Comment by naturalprogrammer** [comment]
Support now available since long. (See the [demos here](https://github.com/naturalprogrammer/spring-lemon) for a pattern). Just missed closing this ticket.
